export const ERRORS = {
    FILE_NOT_SPECIFIED: 'FILE_NOT_SPECIFIED',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    FILE_SYSTEM_API_NOT_SUPPORTED: 'FILE_SYSTEM_API_NOT_SUPPORTED',
    BLOB_NOT_SUPPORTED: 'BLOB_NOT_SUPPORTED',
    MAX_FILE_SIZE_EXCEEDED: 'MAX_FILE_SIZE_EXCEEDED',
    METHOD_NOT_IMPLEMENTED: 'METHOD_NOT_IMPLEMENTED'
};
